
name: Mock Server
description: Mock server for testing
config:
  port: 8080
  delay: 5000 # milliseconds
endpoints:
  /:
    description: Root endpoint
    request_config:
      allowed_methods:
        - GET
        - POST
    response_config:
      status_code: 200
      headers:
        Content-Type: application/json
      body: "{\"message\": \"Hello, World!\"}"
    config:
      ratelimit_config:
        ratelimit: 1 # requests per second
        ratelimit_type: global
      delay: 1000 # milliseconds
      